#!/usr/bin/env python3
"""从 harness/params/jmol_colors.tsv 生成 omgkit-depict 的 palette_data.rs。

为什么生成而不是手写:109 个元素 × 3 个字节,手抄错一个数不会有任何报错 ——
只会让某种元素画出来是别的颜色,而"图上颜色不对"没人会去查表。生成保证
逐位对齐,闸门 `check_palette` 重跑一遍再逐字节比,脱钩当场红。

数据出处与两源核对写在 tsv 的头注释里。

**行末注释前只留一个空格** —— 生成出来的文件也归 `cargo fmt` 管,写两个空格
它会收成一个,于是"重跑一遍逐字节相同"那道闸在 `cargo fmt` 之后必红,而两边
其实说的是同一张表。

用法:
    python3 harness/gen_palette.py
    python3 harness/gen_palette.py --out /tmp/x.rs   # 闸门比对用
"""

from __future__ import annotations

import argparse
import pathlib
import sys

# 元素表的长度(0 是 SMILES 通配原子 `*`,1..=118 是元素)。与
# crates/omgkit-core/src/element_data.rs 一致 —— 对不上时下面会报错退出。
TABLE_LEN = 119

# Jmol 给表外元素的颜色:deeppink。**不是"这个元素是粉的",是"表里没有"。**
# 取自 3Dmol.js `colors.ts` 的 `defaultColor: 0xff1493`。
UNKNOWN = (0xFF, 0x14, 0x93)

HEADER = '''// @generated by harness/gen_palette.py — 请勿手工编辑,改了会被下次生成覆盖。
//
// 数据来自 Jmol 的 CPK 配色表,经两份互相独立的转录逐项核对后入库;
// 出处、核对方式、以及 110-118 为什么是 deeppink,全写在
// harness/params/jmol_colors.tsv 的头注释里。
//
// 重新生成:python3 harness/gen_palette.py

/// 按原子序数索引的 CPK 颜色,RGB 各一字节。索引 0 是 SMILES 通配原子 `*`。
pub(crate) static CPK: [[u8; 3]; {n}] = [
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    root = pathlib.Path(__file__).resolve().parent.parent
    ap.add_argument("--tsv", type=pathlib.Path,
                    default=root / "harness/params/jmol_colors.tsv")
    ap.add_argument("--out", type=pathlib.Path,
                    default=root / "crates/omgkit-depict/src/palette_data.rs")
    args = ap.parse_args()

    rows: list[tuple[int, str, tuple[int, int, int]]] = []
    for lineno, line in enumerate(args.tsv.read_text().splitlines(), start=1):
        if not line.strip() or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 3:
            print(f"{args.tsv}:{lineno}: 该有三列,读到 {len(parts)} 列", file=sys.stderr)
            return 1
        z, sym, hexv = int(parts[0]), parts[1], parts[2]
        rgb = tuple(int(hexv[i:i + 2], 16) for i in (0, 2, 4))
        rows.append((z, sym, rgb))  # type: ignore[arg-type]

    # 原子序数必须从 1 起连号。断号会让下面按 z 填表时静默留一个 deeppink 的洞。
    if [z for z, _, _ in rows] != list(range(1, len(rows) + 1)):
        print(f"{args.tsv}: 原子序数不是从 1 起的连号", file=sys.stderr)
        return 1
    if len(rows) >= TABLE_LEN:
        print(f"{args.tsv}: 有 {len(rows)} 行,装不进长 {TABLE_LEN} 的表", file=sys.stderr)
        return 1

    table: list[tuple[int, int, int]] = [UNKNOWN] * TABLE_LEN
    symbol: list[str | None] = [None] * TABLE_LEN
    for z, sym, rgb in rows:
        table[z] = rgb
        symbol[z] = sym

    out = [HEADER.format(n=TABLE_LEN)]
    for z in range(TABLE_LEN):
        r, g, b = table[z]
        if symbol[z] is None:
            # 表外的那些照实写出来,别让读者以为 Jmol 真给它们定了粉色
            note = "*(通配原子)" if z == 0 else f"Z={z}"
            tail = f" // {note} —— Jmol 表里没有,取未知元素色"
        else:
            tail = f" // {symbol[z]}"
        out.append(f"    [0x{r:02x}, 0x{g:02x}, 0x{b:02x}],{tail}\n")
    out.append("];\n")

    args.out.write_text("".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
