#!/usr/bin/env python3
"""从 RDKit 源码抽取元素数据,生成 omgkit-core 的 element_data.rs。

为什么生成而不是手写:默认价表直接决定 L2 的隐式氢推断,手抄一个数字错了
会在 ChEMBL 差分测试里表现为几千条莫名其妙的分歧,极难定位。生成保证
逐位对齐,且可复现。

数据溯源:
  RDKit `Code/GraphMol/atomic_data.cpp` 的 `periodicTableAtomData` 原始串,
  其数据本身来自 Blue Obelisk Data Repository (BODR)。
  RDKit 为 BSD-3-Clause。

列格式(由 atomic_data.cpp:229 `atomicData::atomicData()` 逐字段读出):
  1  原子序数
  2  元素符号
  3  周期 (row)
  4  共价半径 rCov
  5  rB0
  6  范德华半径 rVdw
  7  原子量
  8  外层电子数
  9  最常见同位素
  10 最常见同位素质量
  11+ 默认价列表(变长;-1 表示无价约束)

用法:
    python3 harness/gen_elements.py \
        --rdkit ../rdkit \
        --out crates/omgkit-core/src/element_data.rs
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

BLOCK_RE = re.compile(r'R"DAT\((.*?)\)DAT"', re.DOTALL)

HEADER = '''// @generated by harness/gen_elements.py — 请勿手工编辑,改了会被下次生成覆盖。
//
// 数据来自 Blue Obelisk Data Repository (BODR),经 RDKit
// `Code/GraphMol/atomic_data.cpp`(BSD-3-Clause)转录;提取自版本 {version}。
// 重新生成的用法见 harness/gen_elements.py。

use crate::element::Element;

/// 按原子序数索引的元素表。索引 0 是 SMILES 通配原子 `*`。
pub(crate) static ELEMENTS: [Element; {n}] = [
'''


def parse(src: str) -> tuple[list[dict], dict[str, int]]:
    """返回 (按序数去重后的元素行, 别名符号 → 原子序数)。

    只解析 `periodicTableAtomData` 的区段。同一文件后面还有
    `isotopesAtomData`,列格式不同,混进来会把表撑坏。

    RDKit 对 113/115 号各有两行(新旧 IUPAC 符号 Nh/Uut、Mc/Uup)。
    实测 `GetElementSymbol(113) == "Nh"`,即**首行为准**;而 `Uut` 仍能
    反查到 113。此处照此实现。
    """
    start = src.find("periodicTableAtomData")
    if start < 0:
        sys.exit("未找到 periodicTableAtomData")
    end = src.find(')DAT";', start)
    if end < 0:
        sys.exit("未找到 periodicTableAtomData 的结束标记")
    region = src[start : end + 6]

    blocks = BLOCK_RE.findall(region)
    if not blocks:
        sys.exit('未在 periodicTableAtomData 区段中找到 R"DAT(...)DAT" 数据块')

    raw: list[dict] = []
    for block in blocks:
        for line in block.splitlines():
            # 分隔符是空白;boost char_separator 默认丢弃空 token
            tok = line.split()
            if len(tok) < 10:
                continue
            if not tok[0].lstrip("-").isdigit():
                continue
            raw.append(
                {
                    "anum": int(tok[0]),
                    "symbol": tok[1],
                    "row": int(tok[2]),
                    "rcov": float(tok[3]),
                    "rb0": float(tok[4]),
                    "rvdw": float(tok[5]),
                    "mass": float(tok[6]),
                    "outer_electrons": int(tok[7]),
                    "common_isotope": int(tok[8]),
                    "common_isotope_mass": float(tok[9]),
                    "valences": [int(v) for v in tok[10:]],
                }
            )

    rows: list[dict] = []
    aliases: dict[str, int] = {}
    seen_anum: set[int] = set()
    for r in raw:
        if r["anum"] in seen_anum:
            aliases[r["symbol"]] = r["anum"]  # 旧 IUPAC 占位符号
            continue
        seen_anum.add(r["anum"])
        rows.append(r)
    return rows, aliases


def emit(rows: list[dict], aliases: dict[str, int], version: str,
         early: list[bool] | None = None) -> str:
    rows.sort(key=lambda r: r["anum"])

    # 完整性检查:原子序数必须 0..=N 连续,否则按序数索引的数组会错位
    for i, r in enumerate(rows):
        if r["anum"] != i:
            sys.exit(f"原子序数不连续:位置 {i} 处为 {r['anum']}(表按序数索引,必须连续)")

    out = [HEADER.format(n=len(rows), version=version)]
    for r in rows:
        vals = ", ".join(str(v) for v in r["valences"]) or ""
        out.append(
            "    Element {{\n"
            "        atomic_num: {anum},\n"
            '        symbol: "{symbol}",\n'
            "        period: {row},\n"
            "        rcov: {rcov!r},\n"
            "        rvdw: {rvdw!r},\n"
            "        mass: {mass!r},\n"
            "        outer_electrons: {oe},\n"
            "        common_isotope: {ci},\n"
            "        common_isotope_mass: {cim!r},\n"
            "        valences: &[{vals}],\n"
            "    }},\n".format(
                anum=r["anum"],
                symbol=r["symbol"],
                row=r["row"],
                rcov=r["rcov"],
                rvdw=r["rvdw"],
                mass=r["mass"],
                oe=r["outer_electrons"],
                ci=r["common_isotope"],
                cim=r["common_isotope_mass"],
                vals=vals,
            )
        )
    out.append("];\n\n")

    # 符号 → 原子序数。解析器的热路径,用 match 让 rustc 生成
    # 按长度+前缀分派的跳转,而不是线性扫描 119 项。
    out.append(
        "/// 元素符号 → 原子序数。大小写敏感;芳香小写符号由调用方先行归一化。\n"
        "pub(crate) fn symbol_to_atomic_num(symbol: &str) -> Option<u8> {\n"
        "    Some(match symbol {\n"
    )
    seen: set[str] = set()
    for r in rows:
        sym = r["symbol"]
        if sym in seen:
            continue
        seen.add(sym)
        out.append(f'        "{sym}" => {r["anum"]},\n')
    if aliases:
        out.append("        // 旧 IUPAC 占位符号,保留可反查\n")
        for sym, anum in sorted(aliases.items()):
            if sym not in seen:
                out.append(f'        "{sym}" => {anum},\n')
    out.append("        _ => return None,\n    })\n}\n")

    if early is not None:
        out.append(
            "\n/// 元素是否在周期表中位于碳的左侧。\n"
            "///\n"
            "/// kekulize 标记双键候选时要用:这些元素的形式电荷对可用价的影响\n"
            "/// 方向与右侧元素相反,算默认价时得先把电荷取反。\n"
            "pub(crate) static IS_EARLY_ATOM: [bool; %d] = [\n" % len(early)
        )
        for i, v in enumerate(early):
            out.append(f"    {str(v).lower()}, // #{i}\n")
        out.append("];\n")

    return "".join(out)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--rdkit", required=True, type=pathlib.Path, help="RDKit 源码根目录")
    ap.add_argument("--out", required=True, type=pathlib.Path)
    args = ap.parse_args()

    data_file = args.rdkit / "Code" / "GraphMol" / "atomic_data.cpp"
    if not data_file.is_file():
        sys.exit(f"找不到 {data_file}")

    rows, aliases = parse(data_file.read_text(encoding="utf-8", errors="replace"))

    # isEarlyAtom 表:同样从源码抽取而非手抄
    early = None
    atom_cpp = args.rdkit / "Code" / "GraphMol" / "Atom.cpp"
    if atom_cpp.is_file():
        text = atom_cpp.read_text(errors="replace")
        m = re.search(r"bool isEarlyAtom\(int atomicNum\)\s*\{.*?\{(.*?)\};", text, re.DOTALL)
        if m:
            early = [tok == "true" for tok in re.findall(r"\b(true|false)\b,", m.group(1))]

    # 版本在顶层 CMakeLists.txt 里(versions.h 只有 extern 声明,值在构建期注入)
    version = "unknown"
    cml = args.rdkit / "CMakeLists.txt"
    if cml.is_file():
        text = cml.read_text(errors="replace")
        parts = {}
        for key in ("Year", "Month", "Revision", "RevisionModifier"):
            m = re.search(rf'set\(RDKit_{key}\s+"([^"]*)"\)', text)
            if m:
                parts[key] = m.group(1)
        if {"Year", "Month", "Revision"} <= parts.keys():
            version = f"{parts['Year']}.{parts['Month']}.{parts['Revision']}"
            if parts.get("RevisionModifier"):
                version += parts["RevisionModifier"]

    # 注意:源码版本必须与已安装的 rdkit 一致。不一致时,元素表来自一个版本、
    # 差分基准来自另一个版本,两者的差异会被误读成本实现的分歧。
    try:
        import rdkit as _rdkit

        installed = _rdkit.__version__
    except Exception:  # pragma: no cover
        installed = None
    if installed and version != "unknown" and installed != version:
        sys.exit(
            f"版本不一致:源码 {version},已安装 rdkit {installed}。\n"
            f"差分测试会拿两个版本互相对照,必然产生假分歧。\n"
            f"修法:cd <rdkit-src> && git fetch --depth 1 origin tag Release_"
            f"{installed.replace('.', '_')} && git checkout Release_"
            f"{installed.replace('.', '_')}"
        )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(emit(rows, aliases, version, early), encoding="utf-8")

    n_val = sum(1 for r in rows if r["valences"] not in ([], [-1]))
    print(f"已写出 {args.out}")
    print(f"  元素数: {len(rows)}(含 0 号通配原子)")
    print(f"  有明确默认价的元素: {n_val}")
    print(f"  别名符号: {sorted(aliases) or '无'}")
    print(f"  isEarlyAtom 表: {len(early) if early else 0} 项")
    print(f"  RDKit 版本: {version}")


if __name__ == "__main__":
    main()
